### ISSUE TITLE
Deploy To Heroku Error

### ISSUE THREAD

**Issue by jontheophilus** [chrisckchang/mean-contactlist#1]
I'm trying to deploy your example code. It appears the app is crashing on start.

Here is the Heroku log:

![image](https://cloud.githubusercontent.com/assets/420029/14893940/4a3cee9c-0d3f-11e6-9a57-6e6697ba8eb9.png)

**Comment by chrisckchang** [comment]
We recently changed the environment variable from MONGOLAB_URI to MONGODB_URI. Should be fixed with https://github.com/chrisckchang/mean-contactlist/commit/6193522f82e12e1ba7bbe73d6e5bd4fd3901db86. Can you give it a try?

**Comment by jontheophilus** [comment]
yes - this is now fixed. Thanks for the quick response!
